### ISSUE TITLE
#2 랜덤 닉네임 띄어쓰기

### ISSUE THREAD

**Issue by hyunjong-96** [bbangmap/BBangMap-Server#56]
- ![image](https://user-images.githubusercontent.com/57162257/144263017-0f8f4970-4b80-4642-9ae3-d9365c07f0f9.png)

**Comment by soleu** [comment]
이 부분은 랜덤 닉네임 문구 관련 기획에 수정 맡겼는데, 기획 문구 수정 후 수정 하겠습니다:)

**Comment by hyunjong-96** [comment]
닉네임 만들때 파일명을 통해서 불러오던데 파일은 어디에 있나요??

**Comment by soleu** [comment]
BBangMap-Server/BBangMap-Server/src/user/data/
경로에서 adjective.txt, second.txt, bread.txt 순으로 불러오고 있습니다
